### ISSUE TITLE
One Pedal Driving article is incorrect

### ISSUE THREAD

**Issue by sean256** [electrichasgoneaudi/electrichasgoneaudi.github.io#2]
> One pedal driving is less efficient since you lose energy compared to coasting.

Sources against this baseless claim:

Using Science: [Evaluation of regenerative braking based on single-pedal control for electric vehicles](https://link.springer.com/content/pdf/10.1007/s11465-019-0546-x.pdf)

[What is One-Pedal Driving and How Does it Work?](https://www.jdpower.com/cars/shopping-guides/what-is-one-pedal-driving-and-how-does-it-work)

Also...

> Many less advanced EVs support one pedal driving meaning that when you lift the foot from the accelerator

What does this statement even mean? A different feature is "less advanced?"

**Comment by TheTechArch** [comment]
@sean256 thanks for your feedback. The article is now updated and I hope it is more clearer why one-pedal driving is less efficient than coasting. 

https://electrichasgoneaudi.net/guides/onepedaldriving/

Se also this article with calculations
https://electrichasgoneaudi.net/guides/regen/
